import React from "react";
import "./design.css";

function Soundtable() {
  return (
    <body>
      <body className="flex-noJust">
      <div className="title">Handwritten Digit Generator
</div>
<br/><br/>
      <div className="flex">
        <div className="left-half-noDash">
          <div className="disc">
            Working off the <a href="https://en.wikipedia.org/wiki/MNIST_database" target="_blank" rel="noreferrer">MNIST database</a>
            , I used <a href="https://www.tensorflow.org/" target="_blank" rel="noreferrer">TensorFlow</a>{" "}
            to create a conditional <a href="https://en.wikipedia.org/wiki/Variational_autoencoder" target="_blank" rel="noreferrer">variational auto-encoder</a>{" "}
            that was able to generate its own images. After sampling a latent vector from a random 
            normal distribution, the network's generated images had an accuracy rating of 98%, when 
            judged by Brown's MNIST discriminator. None of the images on the right were given to the 
            program, but generated by the computer after it studied over 60,000 samples of 
            handwritten digits.
          </div>
        </div>{" "}
        <img src="https://i.imgur.com/8EPBv3q.jpg" className="smallimg"></img>
      </div>
      <div className="flex2">
        <img src="https://i.imgur.com/7STGuRp.png" className="smallerimg"/>
        <div className="left-half-noDash">
          <div className="disc">
            These images are created by passing input to a neural network (the encoder) which 
            generates a compressed latent vector that is then passed through another neural network 
            (the decoder) to generate a new image. Once trained off of a dataset of example images, the
            networks are able to generate realistic output by sampling latent space.
          </div>
        </div>
      </div>
    </body>
      <div className="footer2">credit to brown <a href="https://brown-deep-learning.github.io/dl-website-f22/" target="_blank" rel="noreferrer">cs 1470</a>, fall 2021</div>
    </body>
  );
}

export default Soundtable;
